apiVersion: v1
kind: Service
metadata:
  name: "api"
  labels:
    app: api
    {{- include "wordsmith.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.targetPort }}
      name: api
  selector:
    app: api
    {{- include "wordsmith.selectorLabels" . | nindent 4 }}
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "wordsmith.fullname" . }}-api"
  labels:
    app: api
    {{- include "wordsmith.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: api
      {{- include "wordsmith.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: api
        {{- include "wordsmith.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image }}:{{ .Values.api.tag }}"
          ports:
            - containerPort: {{ .Values.api.targetPort }}
              name: api